hide_search=true
dynamic_lines=true
mode=dmenu
prompt=
normal_window=true
style=/home/hiroshi/.config/wofi/wifimenu.css
cache_file=/dev/null
lines=7
width=25%
hide_scroll=true
halign=center
content_halign=center